import type { MetaRecord } from 'nextra';

const separator = (title: string) => ({ type: 'separator', title });

const meta = {
  index: {
    title: 'Home',
    type: 'page',
    theme: {
      layout: 'full',
      toc: false,
      footer: false,
      copyPage: false,
    },
  },
  blog: {
    title: 'Blog',
    href: '/blog',
    type: 'page',
    display: 'hidden',
  },
  '#about': separator('About'),
  about: 'About Vovk.ts 🚧',
  why: 'Why Vovk.ts? 🚧',
  performance: 'Overhead Performance 🚧',
  '#getting-started': separator('Getting Started'),
  'quick-install': 'Quick Start 🚧',
  'manual-install': 'Manual Install 🚧',
  '#essentials': separator('Essentials'),
  segment: 'Segment',
  procedure: 'Remote Procedure',
  'req-vovk': <><code className='code'>req.vovk</code>{' '}<span className="leading-6">Interface</span></>,
  response: 'Response',
  fn: 'Local Procedure 🚧',
  decorator: 'Custom Decorators',
  jsonlines: 'JSON Lines',
  schema: 'Schema',
  inference: 'Type Inference',
  openapi: 'OpenAPI Specification',
  'function-calling': 'Deriving AI Tools 🚧',
  multitenant: 'Multitenancy (Tutorial)',
  '#codegen': separator('TypeScript RPC Codegen'),
  typescript: 'TypeScript Client',
  'client-validation': 'Client-side Validation 🚧',
  imports: 'Imports Customization',
  composed: 'Composed Clients',
  segmented: 'Segmented Clients',
  '#advanced-codegen': separator('Codegen Extras'),
  codegen: 'OpenAPI Mixins 🚧',
  python: 'Python Client 🧪',
  rust: 'Rust Client 🧪',
  templates: 'Codegen Templates Reference',
  '#examples': separator('Examples'),
  github_link: {
    title: 'Random Examples',
    href: 'https://examples.vovk.dev',
  },
  'hello-world': '"Hello World!" 🚧',
  llm: 'LLM Chats 🚧',
  mcp: 'MCP Handler 🚧',
  'realtime-ui': { title: 'Realtime UI (DRAFTS) 🚧', theme: { collapsed: true, copyPage: true } },
  '#cli': separator('CLI & Configuration'),
  config: 'Config File',
  bundle: <code className="nextra-code">vovk bundle</code>,
  dev: <code className="nextra-code">vovk dev</code>,
  generate: <code className="nextra-code">vovk generate</code>,
  init: <code className="nextra-code">vovk init</code>,
  new: <code className="nextra-code">vovk new</code>,
  '#etc': separator('Reference'),
  packages: 'Packages 🚧',
  'api-ref': 'API Reference 🚧',
} satisfies MetaRecord;

export default meta;
