import type { MetaRecord } from 'nextra';

const separator = (title: string) => ({ type: 'separator', title });

const meta = {
  index: {
    title: 'Home',
    type: 'page',
    theme: {
      layout: 'full',
      toc: false,
      footer: false,
      copyPage: false,
    },
  },
  blog: {
    title: 'Blog',
    href: '/blog',
    type: 'page',
    display: 'hidden',
  },
  '#about': separator('About'),
  about: 'About Vovk.ts 🚧',
  why: 'Why Vovk.ts? 🚧',
  performance: 'Overhead Performance',
  '#getting-started': separator('Getting Started'),
  'quick-install': 'Quick Start',
  'manual-install': 'Manual Install',
  'hello-world': '"Hello World!" Example',
  '#common': separator('Common'),
  'rpc-module': 'RPC Module 🚧',
  schema: 'Schema',
  validation: 'Validation',
  inference: 'Type Inference',
  '#server-side': separator('Server-Side'),
  segment: 'Segment',
  controller: 'Controller',
  '#typescript': separator('TypeScript Client'),
  typescript: 'TypeScript RPC',
  composed: 'Composed Client',
  segmented: 'Segmented Client',
  imports: 'Imports Customization',
  '#other-clients': separator('Other Clients'),
  python: 'Python RPC 🧪',
  rust: 'Rust RPC 🧪',
  '#ai': separator('AI Applications'),
  llm: 'LLM Completions',
  'function-calling': 'Function Calling 🚧',
  mcp: 'MCP Handler 🚧',
  'realtime-ui': { title: 'Realtime UI (DRAFTS) 🚧', theme: { collapsed: true, copyPage: true } },
  '#cli': separator('Config & CLI'),
  config: 'Config',
  cli: 'CLI',
  bundle: <code className="nextra-code">vovk bundle</code>,
  dev: <code className="nextra-code">vovk dev</code>,
  generate: <code className="nextra-code">vovk generate</code>,
  init: <code className="nextra-code">vovk init</code>,
  new: <code className="nextra-code">vovk new</code>,
  '#etc': separator('etc.'),
  openapi: 'OpenAPI Specification',
  multitenant: 'Multitenancy 🧪',
  codegen: 'Codegen via OpenAPI Mixins 🚧',
  templates: 'Client Templates',
  packages: 'Packages',
  'api-ref': 'API Reference 🚧',
  '#guides': separator('Random Recipes & Guides'),
  authorization: 'Authorization with Decorators',
  proxy: 'Proxy Endpoints',
  nestjs: 'API Client for NestJS 🚧',
} satisfies MetaRecord;

export default meta;
